require "mem"
require "mongoid"

require "rack/mongoid_adapter/application"
require "rack/mongoid_adapter/controllers/base"
require "rack/mongoid_adapter/controllers/single_resource_controller"
require "rack/mongoid_adapter/controllers/create_controller"
require "rack/mongoid_adapter/controllers/destroy_controller"
require "rack/mongoid_adapter/controllers/index_controller"
require "rack/mongoid_adapter/controllers/show_controller"
require "rack/mongoid_adapter/controllers/update_controller"
require "rack/mongoid_adapter/version"
